### ISSUE TITLE
Rename Skia.FMX

### ISSUE THREAD

**Issue by 1Dragon** [HemulGM/QRScan#1]
hello HemulGM,

you must rename skia.fmx to FMX.Skia on delphi 11.3

thanks for all your projects, they are all great.

**Comment by HemulGM** [comment]
Delphi 11 has nothing to do with it. Skia modules have been renamed in version 6.0.0. The same version was included in the Delphi distribution, but only in version 12. Not everyone uses version 12 of Delphi and/or version 6.0.0 of Skia. Because version 6.0.0 of Skia is a Beta version.
